version: '{build}'
clone_depth: 10

branches:
  only:
    - master
    - /.*-[0-9]+\..*/

environment:
  MAVEN_OPTS: "-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn"

cache:
  - C:\Users\appveyor\.m2\repository

image: Visual Studio 2015

platform:
  - x64

build_script:
  - ps: .\.appveyor\build.ps1
