version: '{build}'
clone_depth: 10

cache:
  - C:\Users\appveyor\.m2\repository

environment:
  MAVEN_OPTS: "-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn"

platform:
  - x64

branches:
  only:
    - master
    - /.*-[0-9]+\..*/
init:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

build_script:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/scijava/scijava-scripts/appveyor/appveyor-build.ps1'))
